# Generated by Django 4.2.1 on 2023-05-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_alter_student_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Res",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("time", models.CharField(max_length=30)),
            ],
        ),
    ]
